name: Go CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'  # Update to match the version in your go.mod

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('backend/go.sum') }}  # Correct path
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install dependencies
      working-directory: backend
      run: go mod tidy

    - name: Run tests
      working-directory: backend
      run: go test ./...  # Run tests in all packages

    - name: Build
      working-directory: backend
      run: go build -o todo-app .  # Build your application
