name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.18'
    - name: Install dependencies
      run: go mod tidy
    - name: Run tests
      run: |
        # You can add tests here
        echo "No tests implemented yet"

